import re

with open('_posts/ctf-writeups/2026-06-29-brunner-ctf-2026.md', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    'Chào mừng các bạn đến với writeup giải **BrunnerCTF 2026**! Theo như thông báo từ ban tổ chức, năm nay giải đấu mở rộng quy mô từ một tiệm bánh nhỏ thành một tập đoàn kỳ lân với chủ đề *"Brunnerne goes corporate"*.': 'Welcome to the **BrunnerCTF 2026** writeup! According to the organizers, this year\'s competition has expanded from a small bakery into a unicorn corporation with the theme *"Brunnerne goes corporate"*.',
    'Giải đấu mang đến những thử thách vô cùng thú vị và "ngon miệng" cho tất cả mọi người, từ những "thực tập sinh CTF" mới vào nghề cho đến các "phó chủ tịch điều hành cấp cao". Dưới đây là phần tóm tắt và lời giải chi tiết cho các thử thách mà mình đã giải quyết được. Cùng xem nhé!': 'The competition brings extremely interesting and "delicious" challenges for everyone, from newly-hired "CTF interns" to "senior executive vice presidents". Below is a summary and detailed solution for the challenges I managed to solve. Let\'s dive in!',
    'Một bài khởi động đơn giản, đề bài cung cấp file `Brunnerne_Employee_Discount_Newsletter_2026.hta`': 'A simple warm-up challenge, the problem provides the file `Brunnerne_Employee_Discount_Newsletter_2026.hta`',
    'Đây là định dạng tệp tin cho phép chạy mã nguồn HTML, CSS và JavaScript như một ứng dụng độc lập trên hệ điều hành Windows, có quyền truy cập hệ thống thay vì bị giới hạn trong trình duyệt web.': 'This is a file format that allows running HTML, CSS, and JavaScript source code as an independent application on the Windows operating system, with system access instead of being restricted within a web browser.',
    'Mở ra bằng notepad, mình thấy 1 đoạn script gọi tiến trình powershell để tải 1 đoạn script khác về và thực thi nó.': 'Opening it with notepad, I found a script that calls a powershell process to download another script and execute it.',
    'Truy cập vào đường link, mình tìm thấy một đoạn mã được obfuscate, đoạn mã được dùng để vượt qua ưhệ thống giám sát, sau đó tải về 1 đoạn script nữa cho giai đoạn tấn công tiếp theo.': 'Accessing the link, I found an obfuscated code snippet used to bypass the monitoring system, which then downloads yet another script for the next attack phase.',
    'Tiếp tục truy cập vào đường link này để lấy flag cho câu này.': 'Continuing to access this link gives us the flag for this challenge.',
    'Một bài khởi động đơn giản nữa, đề bài cung cấp file `Game.jpg` và `SaveGame1`.': 'Another simple warm-up challenge, providing the files `Game.jpg` and `SaveGame1`.',
    'Mở bức ảnh lên, mình thấy lưới nhân vật có một số ô đã được mở khóa, trong khi các ô còn lại bị làm mờ.': 'Opening the image, I noticed the character grid has some slots unlocked, while the rest are blurred out.',
    'Đọc file `SaveGame1` dưới dạng hexdump và xem ở phần cuối của file, mình tìm thấy mảng dữ liệu lưu trữ trạng thái của danh sách nhân vật. Trong đó, byte `03` đại diện cho trạng thái đã mở khóa, còn `00` là chưa mở khóa.': 'Reading the `SaveGame1` file as a hexdump and looking at the end of the file, I found a data array storing the status of the character list. In this array, the byte `03` represents the unlocked state, while `00` is locked.',
    'Sử dụng một đoạn script Python nhỏ để trích xuất đoạn dữ liệu này, mình đổi các giá trị `03` thành bit `1` và `00` thành bit `0`, sau đó gom thành từng cụm 8 bit để dịch ngược ra bảng mã ASCII.': 'Using a small Python script to extract this data snippet, I changed the `03` values to bit `1` and `00` to bit `0`, then grouped them into 8-bit clusters to decode back to ASCII.',
    'Đề bài cung cấp file `rubiks.pcapng`': 'The challenge provides the file `rubiks.pcapng`',
    'Đây là tệp tin chứa dữ liệu bắt gói tin mạng, cụ thể là luồng giao tiếp Bluetooth Low Energy (BLE) giữa một chiếc QiYi Smart Cube và ứng dụng điện thoại.': 'This is a network packet capture file, specifically containing the Bluetooth Low Energy (BLE) communication stream between a QiYi Smart Cube and a mobile app.',
    'Mở file bằng Wireshark, mình dùng filter `btatt.opcode == 0x1b` để lọc ra các gói tin BLE ATT Handle Value Notification. Đây là các gói tin mà khối Rubik tự động gửi về app điện thoại mỗi khi có một mặt vừa bị xoay.': 'Opening the file in Wireshark, I used the filter `btatt.opcode == 0x1b` to extract BLE ATT Handle Value Notification packets. These are packets that the Rubik\'s Cube automatically sends to the mobile app whenever a face is rotated.',
    '- Click vào một gói tin bất kỳ, nhìn xuống bảng Packet Details ở nửa dưới màn hình.\n- Mở rộng nhánh **Bluetooth Attribute Protocol.**\n- Nhấp chuột phải vào dòng **Value** và chọn *Apply as Column*.\n- Chọn menu **File -> Export Packet Dissections -> As CSV....**': '- Click on any packet, and look down at the Packet Details pane at the bottom.\n- Expand the **Bluetooth Attribute Protocol** branch.\n- Right-click on the **Value** line and select *Apply as Column*.\n- Go to **File -> Export Packet Dissections -> As CSV....**',
    'Giờ cùng tìm cách giải mã các đoạn giá trị này nào': 'Now let\'s figure out how to decode these value snippets.',
    'Mình đọc file CSV, lấy cột chứa mã hex và dùng thuật toán AES-128-ECB với khóa tĩnh của hãng QiYi để giải mã về dữ liệu gốc, Xóa đi 7 byte rác, cắt 27 byte tiếp theo thành 54 con số rồi dịch ngược về 54 chữ cái tương ứng trên các mặt Rubik và in ra': 'I read the CSV file, extracted the hex code column, and used the AES-128-ECB algorithm with QiYi\'s static key to decrypt it back to the original data. After removing 7 junk bytes, I sliced the next 27 bytes into 54 numbers, then decoded them back into the 54 corresponding letters on the Rubik\'s Cube faces and printed them out.',
    'Nếu chăm chỉ, bạn có thể dán các chuỗi này vào API của trang [**VisualCube**](https://cube.rider.biz/visualcube.php) hoặc phần mềm của hãng QiYi để render ra hình 3D rồi tự căng mắt so sánh từng bước. Nhưng vì lười, mình quyết định sử dụng hàm `solve` của thư viện `kociemba` trong Python để máy tính tự động dò đường đi ngắn nhất giữa 2 chuỗi liên tiếp.': 'If you are hard-working, you can paste these strings into the API of [**VisualCube**](https://cube.rider.biz/visualcube.php) or QiYi\'s software to render a 3D model and manually compare each step. But out of laziness, I decided to use the `solve` function from the `kociemba` library in Python to let the computer automatically find the shortest path between 2 consecutive strings.',
    "Mình cũng tự động gộp các bước xoay bị trùng lặp (ví dụ: xoay `F` rồi lại xoay `F` thì gom gọn thành `F2`).": "I also automatically merged redundant rotation steps (for example: rotating `F` and then `F` again is simplified to `F2`).",
    "Chuỗi thao tác thu được sau khi rút gọn hoàn chỉnh là: F2, U2, B', R2, B', L, D2, R, F2, U, B2, D, R2, B2, D', B2, U, F2, U, B": "The sequence of operations obtained after complete simplification is: F2, U2, B', R2, B', L, D2, R, F2, U, B2, D, R2, B2, D', B2, U, F2, U, B",
    'Đề bài cung cấp một file pcap nữa `the-missing-recipe.pcap`': 'The challenge provides another pcap file `the-missing-recipe.pcap`',
    'Mở file bằng Wireshark, mình phát hiện có dấu hiệu leak dữ liệu qua giao thức DNS thông qua truy vấn đến các subdomain của **targwuwrnhos.com**.': 'Opening the file in Wireshark, I detected signs of data exfiltration over the DNS protocol through queries to subdomains of **targwuwrnhos.com**.',
    '- Click vào một gói tin bất kỳ, nhìn xuống bảng Packet Details ở nửa dưới màn hình.\n- Mở rộng nhánh **Queries.**\n- Nhấp chuột phải vào dòng **Name** và chọn *Apply as Column*.\n- Chọn menu **File -> Export Packet Dissections -> As CSV....**': '- Click on any packet, and look down at the Packet Details pane at the bottom.\n- Expand the **Queries** branch.\n- Right-click on the **Name** line and select *Apply as Column*.\n- Go to **File -> Export Packet Dissections -> As CSV....**',
    'Mở file CSV vừa xuất ra, mình nhìn qua các subdomain thu được và nhận thấy đặc trưng của mã **Base32**.': 'Opening the exported CSV file, I glanced through the obtained subdomains and noticed characteristics of **Base32** encoding.',
    'Các subdomain này thực chất được chia thành hai luồng dữ liệu riêng biệt, bắt đầu bằng chuỗi': 'These subdomains are actually split into two separate data streams, starting with the string',
    'Có vẻ chuỗi này là 1 file pack zstd, Thank you Gemini.': 'It seems this string is a zstd packed file, Thank you Gemini.',
    'Mình sử dụng đoạn code python sau để lấy 2 luồng mã hóa này, decrypt và unpack nó.': 'I used the following python code to extract these 2 encrypted streams, decrypt and unpack them.',
    'Kết quả thu được một đoạn thông điệp, một đoạn mã hóa và nửa đầu của flag: `brunner{k33p_53nd`.': 'The result yielded a message, an encrypted segment, and the first half of the flag: `brunner{k33p_53nd`.',
    'Đoạn thông điệp có nhắc đến việc gửi encryption key.': 'The message mentions sending an encryption key.',
    'Quay lại Wireshark, đổi filter thành `dns.flags.response == 1 && dns.qry.name contains "targwuwrnhos.com"` để tìm các gói tin phản hồi từ máy chủ C2.': 'Going back to Wireshark, I changed the filter to `dns.flags.response == 1 && dns.qry.name contains "targwuwrnhos.com"` to find response packets from the C2 server.',
    'Mình thấy truy vấn tới **update.targwuwrnhos.com** được server trả về một bản ghi chứa chuỗi Base64 là **KLUv/SAQgQAAQnJ1bm4zckszeUFFU0NCQw==**.': 'I noticed a query to **update.targwuwrnhos.com** where the server returned a record containing the Base64 string **KLUv/SAQgQAAQnJ1bm4zckszeUFFU0NCQw==**.',
    'Tiếp tục lôi chuỗi này ra decrypt và unpack, kết quả trả về là một cụm 16 byte `Brunn3rK3yAESCBC` chính là khóa AES để giải mã payload 2': 'I proceeded to extract this string, decrypt and unpack it, and the result returned a 16-byte block `Brunn3rK3yAESCBC`, which is the AES key to decrypt payload 2.',
    'Sửa lại đoạn python trên 1 chút để lấy mỗi payload 2 và decrypt nó': 'I modified the python script above slightly to only grab payload 2 and decrypt it.',
    'nửa sau của flag: `1ng_th3_me55ag3s}`': 'the second half of the flag: `1ng_th3_me55ag3s}`',
    'Đề bài cung cấp một file là `can-recording-model-3.asc`.': 'The challenge provides a file named `can-recording-model-3.asc`.',
    'Đây là tệp tin chứa bản ghi log mạng CAN bus của một chiếc Tesla Model 3, lưu lại lịch sử các gói tin giao tiếp giữa các thành phần điện tử trên xe.': 'This is a file containing the CAN bus network log record of a Tesla Model 3, saving the history of communication packets between the electronic components on the car.',
    'Mỗi dòng là một gói tin CAN được ghi lại. Cấu trúc của một dòng chuẩn sẽ bao gồm các cột như sau:': 'Each line is a recorded CAN packet. The structure of a standard line includes the following columns:',
    'mình viết một đoạn script python để tách tất cả các bộ phận của thiết bị này ra thành riêng các file riêng dựa trên ID.': 'I wrote a python script to separate all components of this device into their own separate files based on ID.',
    'Mở và kiểm tra sự biến thiên dữ liệu của từng file, mình phát hiện ra một điểm bất thường ở file `ID_3F5.asc`.': 'Opening and checking the data variance of each file, I discovered an anomaly in the file `ID_3F5.asc`.',
    'Cột dữ liệu thứ 4 (tức là Byte 3) liên tục thay đổi qua lại giữa hai giá trị là `18 92 04` và `38 82 0C`, trong khi các byte còn lại gần như giữ nguyên.': 'The 4th data column (which is Byte 3) continuously toggles back and forth between two values `18 92 04` and `38 82 0C`, while the rest of the bytes remain mostly unchanged.',
    'Để nhìn rõ hơn quy luật bật/tắt này, mình dùng thư viện `matplotlib` để vẽ đồ thị dạng sóng dựa vào cột timestamp và trạng thái của Byte 3.': 'To get a clearer view of this on/off pattern, I used the `matplotlib` library to plot a waveform graph based on the timestamp column and the state of Byte 3.',
    'Nhìn vào đồ thị dạng sóng, có thể thấy các xung nhịp ngắn dài xen kẽ nhau tạo thành một dải tín hiệu mã Morse.': 'Looking at the waveform graph, you can see alternating short and long pulses forming a Morse code signal band.',
    'Mình dễ dàng giải mã được thông điệp bí mật là `HIDDEN IN PLAINLIGHT`.': 'I easily decoded the secret message as `HIDDEN IN PLAINLIGHT`.',
    'Bài cung cấp cho mình một thư mục `rootfs` (hệ thống file của người dùng) và một file dump bộ nhớ vật lý `mem.dump`.': 'The challenge provides a `rootfs` folder (the user\'s file system) and a physical memory dump file `mem.dump`.',
    'Sử dụng **ewfmount** với rootfs': 'Using **ewfmount** with rootfs',
    '# Lệnh trên sẽ liệt kê các phân vùng. Tìm phân vùng có định dạng Linux (kích thước lớn nhất) và ghi lại con số ở cột Start.': '# The above command lists the partitions. Find the Linux formatted partition (the largest size) and note the number in the Start column.',
    '# => Kích thước mỗi sector thường là 512 byte => Lấy Start * 512 để ra số byte cần nhảy tới.': '# => Sector size is usually 512 bytes => Multiply Start * 512 to get the byte offset to jump to.',
    'Sau khi mount ổ đĩa, mình cần tìm cách để đọc được file Memory còn lại bằng Volatility 3, Kiểm tra thư mục **/boot**, mình xác định hệ điều hành đang chạy nhân Linux phiên bản **6.12.94+deb13-amd64**': 'After mounting the drive, I needed to find a way to read the remaining Memory file using Volatility 3. Checking the **/boot** directory, I determined the operating system is running Linux kernel version **6.12.94+deb13-amd64**',
    'Truy cập vào repository của Debian và tải xuống gói Debug của Kernel tương ứng: **linux-image-6.12.94+deb13-amd64-dbg**': 'Accessing the Debian repository and downloading the corresponding Kernel Debug package: **linux-image-6.12.94+deb13-amd64-dbg**',
    'Chào mừng các bạn đến với writeup giải BrunnerCTF 2026! Giải đấu năm nay mang chủ đề \'Brunnerne goes corporate\' với rất nhiều thử thách thú vị...': 'Welcome to the BrunnerCTF 2026 writeup! This year\'s competition features the theme \'Brunnerne goes corporate\' with many interesting challenges...'
}

for vn, en in replacements.items():
    text = text.replace(vn, en)

with open('_posts/ctf-writeups/2026-06-29-brunner-ctf-2026.md', 'w', encoding='utf-8') as f:
    f.write(text)

